#!/bin/bash

#date
#cal
#pwd
#ls
#ps aux

# Here i set up some variables

var1=59
var2=sheep
var3=""
fname=leon
sname="R'obinson"

# Here I access the variables

echo $var1
echo $var2
echo $fname
echo $sname

#Here I do a test 

#if [ $var1 = $var2 ]
#then
#     echo  "The test returned true!"
#else
#    echo "The test is false !"
#fi


#Here another test

echo "Checking to see if  USERNAME is M93 "

if [ $USERNAME="M93" ]
then
    echo "Hurrah is true"
else
    echo "Nooo, is false"
fi


#And  another test here 

echo "Checking if Procesor_Level  is greater than 10"
if [ $PROCESSOR_LEVEL -gt 10 ]
then 
echo "True, above 10"
else
echo "Not true, it is below 10"
fi




